---
- name: play to run lookup
  hosts: all

  become: true

  vars:
    etc_hosts: "{{ query('file', '/etc/hosts') }}"
    node_env_host: "{{ lookup('env', 'HOSTNAME') }}"
    ls_command: "{{ lookup('pipe', 'ls -lrt /etc/issue') }}"

  tasks:

    - name: loop and print each line of the var
      debug:
        msg: "{{ item[0] }}"
      loop: "{{ query('lines','cat /etc/hosts') }}"

    - name: print HOSTNAME variable
      debug:
        var: node_env_host

    - name: print ls command
      debug:
        var: ls_command

    - name: list files
      debug:
        msg: "{{ item }}"
      loop: "{{ query('fileglob', '~/.*') }}"
