---
- name: play to run delegate
  hosts: localhost
  gather_facts: false
  tasks:

    - name: set fact for node1
      set_fact:
        target_user: murillo
      delegate_to: node1.example.com
      delegate_facts: true

    - name: print fact on node1
      debug:
        msg: "{{ hostvars['node1.example.com']['target_user'] }}"

    - name: get system info
      command: uname -a
      register: server
    - name: display server
      debug:
        var: server

    - name: get system info
      command: uname -a
      register: local
      delegate_to: node2.example.com
    - name: print local
      debug:
        var: local



