---
# tasks file for web



- name: print the server
  debug:
    msg: "{{ ansible_hostname }}"

- name: ensure SELinux allows httpd connections to a remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: true

- name: ensure httpd is up
  service:
    name: httpd
    state: started

- name: ensure firewall is added
  firewalld:
    service: http
    state: enabled
