- name: use tower API to launch a job
  hosts: localhost
  become: false
  vars:
    tower_user: admin
    tower_pass: password
    tower_host: tower.example.com
    tower_job: vaulted
  tasks:
  - name: launch {{ tower_job }}
    uri:
      url: https://{{ tower_host }}/api/v2/job_templates/{{ tower_job }}/launch/
      method: POST
      validate_certs: no
      return_content: yes
      user: "{{ tower_user }}"
      password: "{{ tower_pass }}"
      force_basic_auth: yes
      status_code: 201
